version: '3.9'
services:
  application:
    build: .
    env_file:
      - .env
    container_name: app
    restart: always
    command: ["./script.sh"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - enrollment

  db:
    image: postgres:15.2-alpine
    container_name: database
    env_file:
      - .env
    restart: always
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge
