version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    links:
      - db
    networks:
      - enrollment


  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge