"""Database creation

Revision ID: 1a2a3deaf0e8
Revises: 
Create Date: 2023-04-21 21:43:29.706490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2a3deaf0e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_type',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('type', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courier',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('Courier type', sa.String(), nullable=True),
            sa.Column('Regions', sa.JSON(), nullable=True),
            sa.Column('Working hours', sa.JSON(), nullable=True),
            sa.ForeignKeyConstraint(['Courier type'], ['courier_type.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier')
    op.drop_table('courier_type')
    # ### end Alembic commands ###
