"""create db2

Revision ID: 22ad8f15a426
Revises: c898051c0c54
Create Date: 2023-04-27 14:17:30.429556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ad8f15a426'
down_revision = 'c898051c0c54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
