"""create db

Revision ID: 7e714bc755c2
Revises: 
Create Date: 2023-04-28 11:34:47.470449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e714bc755c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courier',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('Courier_type', sa.Integer(), nullable=True),
    sa.Column('Regions', sa.JSON(), nullable=True),
    sa.Column('Working_hours', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['Courier_type'], ['courier_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier')
    op.drop_table('courier_type')
    # ### end Alembic commands ###
