"""change db

Revision ID: 8206cf897bb6
Revises: 77cb719a9584
Create Date: 2023-05-06 13:52:13.848485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8206cf897bb6'
down_revision = '77cb719a9584'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Courier_id', sa.Integer(), nullable=True),
    sa.Column('Order_id', sa.Integer(), nullable=True),
    sa.Column('Time', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Courier_id'], ['courier.id'], ),
    sa.ForeignKeyConstraint(['Order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirm_order_Order_id'), 'confirm_order', ['Order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirm_order_Order_id'), table_name='confirm_order')
    op.drop_table('confirm_order')
    # ### end Alembic commands ###
