"""create database

Revision ID: 96b9570c083c
Revises: 
Create Date: 2023-05-14 19:56:06.119652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b9570c083c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
        sa.Column('courier_id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
        sa.Column('courier_type', sa.String(), nullable=True),
        sa.Column('regions', sa.JSON(), nullable=True),
        sa.Column('working_hours', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('courier_id')
    )
    op.create_table('order',
        sa.Column('cost', sa.Integer(), nullable=True),
        sa.Column('delivery_hours', sa.JSON(), nullable=True),
        sa.Column('order_id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
        sa.Column('regions', sa.Integer(), nullable=True),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('completed_time', sa.DateTime(), nullable=True),
        sa.Column('courier_delivers_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('courier')
    # ### end Alembic commands ###
